### PR TITLE
Fix CS

### PR DESCRIPTION
**Pull request by flashios09**

### CODE REVIEW

**Comment by qkdreyer** [comment]
Is this Sublime Text 2 compatibility ? I've no problem using this package.

**Comment by benmatselby** [comment]
I'm not planning on merging this in, as it doesn't add any benefit (in my opinion), and means I have to dedicate a portion of my time to test all of this again before it was released, which I don't really want to do to be honest.

**Comment by flashios09** [comment]
@benmatselby I didn't touch **the logic**, only some **code sniffing warnings**(take a look at **diff**)

> as it doesn't add any benefit (in my opinion)
**Phpcs** also doesn't add any benefit, only some conventions to respect :p

> and means I have to dedicate a portion of my time to test all of this again before it was released
I'm using it on ST3, as i said before i didn't touch **the logic**, it's a **CS FIX**(flake8 complaint about number of lines before each `def`, `class`, using `if ... is ...` instead of `if ... == ... `, using `if ... is not ...` instead of `if ... != ...`)

**Comment by flashios09** [comment]
@qkdreyer No it's not about ST2 compatibility, only **code sniffing fix** for the `phpcs.py` file(doesn't affect the logic/plugin)

**Comment by benmatselby** [comment]
@flashios09 

Just to follow this up so it doesn't look like I'm ignoring it

> Phpcs also doesn't add any benefit, only some conventions to respect :p

I absolutely think Phpcs adds benefit, if there is a defined standard, and working in large teams. It basically makes sure pull requests like this are not raised (in my opinion). I've been consistent in this code, it's just not to your liking (Again, in my opinion). I wasn't aware of flake8 to be fair, as Im mainly a PHP developer, so writing this in python was a means to an end.

I'm not a native python developer, I've learnt it simply to write this plugin. An investigation this evening however, seems to suggest that `==` and `is` are actually semantically different. [reference](https://docs.python.org/3.6/library/stdtypes.html#truth-value-testing) 

Hope this provides some insight into my thinking here

**Pull request closed without merging**
